version: '2'
services:
  rails:
    build: .
    image: my/rails5.2
    container_name: 'rails_app'
    ports:
      - "8080:3000"
    environment:
      APP_ROOT_PASSWORD: 'password'
      APP_DATABASE: 'example'
      APP_DATABASE_USER: 'app'
      APP_DATABASE_PASSWORD: 'development'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    volumes:
      - ./src:/usr/local/src
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: 'rails_db'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'rails_app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'password'
    ports:
      - "13306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql

